export interface UserProfile {
  id: string;
  name: string;
  age: number;
  gender: string;
  religion: string;
  caste: string;
  location: string;
  bio: string;
  photo?: string;
}

export const mockProfiles: UserProfile[] = [
  // Women
  {
    id: '1',
    name: 'Priya Sharma',
    age: 27,
    gender: 'Female',
    religion: 'Hindu',
    caste: 'Brahmin',
    location: 'Mumbai',
    bio: 'Software engineer who loves traveling and cooking',
    photo: 'https://randomuser.me/api/portraits/women/1.jpg',
  },
  {
    id: '2',
    name: 'Ananya Gupta',
    age: 25,
    gender: 'Female',
    religion: 'Hindu',
    caste: 'Gupta',
    location: 'Delhi',
    bio: 'Doctor who enjoys reading and painting',
    photo: 'https://randomuser.me/api/portraits/women/2.jpg',
  },
  {
    id: '3',
    name: 'Neha Reddy',
    age: 28,
    gender: 'Female',
    religion: 'Hindu',
    caste: 'Reddy',
    location: 'Hyderabad',
    bio: 'Architect with love for design and photography',
    photo: 'https://randomuser.me/api/portraits/women/3.jpg',
  },
  {
    id: '4',
    name: 'Aisha Khan',
    age: 29,
    gender: 'Female',
    religion: 'Muslim',
    caste: 'Sunni',
    location: 'Bangalore',
    bio: 'Marketing professional and food enthusiast',
    photo: 'https://randomuser.me/api/portraits/women/4.jpg',
  },
  {
    id: '5',
    name: 'Simran Kaur',
    age: 26,
    gender: 'Female',
    religion: 'Sikh',
    caste: 'Jat',
    location: 'Punjab',
    bio: 'Fashion designer with a passion for dance',
    photo: 'https://randomuser.me/api/portraits/women/5.jpg',
  },
  {
    id: '6',
    name: 'Lakshmi Nair',
    age: 30,
    gender: 'Female',
    religion: 'Hindu',
    caste: 'Nair',
    location: 'Chennai',
    bio: 'Teacher who loves classical music',
    photo: 'https://randomuser.me/api/portraits/women/6.jpg',
  },
  {
    id: '7',
    name: 'Maria Thomas',
    age: 24,
    gender: 'Female',
    religion: 'Christian',
    caste: 'Catholic',
    location: 'Kolkata',
    bio: 'Graphic designer and coffee lover',
    photo: 'https://randomuser.me/api/portraits/women/7.jpg',
  },
  {
    id: '8',
    name: 'Riya Jain',
    age: 31,
    gender: 'Female',
    religion: 'Jain',
    caste: 'Svetambara',
    location: 'Ahmedabad',
    bio: 'Entrepreneur with a love for yoga',
    photo: 'https://randomuser.me/api/portraits/women/8.jpg',
  },
  {
    id: '9',
    name: 'Sana Mirza',
    age: 23,
    gender: 'Female',
    religion: 'Muslim',
    caste: 'Shia',
    location: 'Pune',
    bio: 'Student and aspiring writer',
    photo: 'https://randomuser.me/api/portraits/women/9.jpg',
  },
  {
    id: '10',
    name: 'Deepika Menon',
    age: 32,
    gender: 'Female',
    religion: 'Hindu',
    caste: 'Menon',
    location: 'Jaipur',
    bio: 'Interior designer who loves hiking',
    photo: 'https://randomuser.me/api/portraits/women/10.jpg',
  },
  // Men
  {
    id: '11',
    name: 'Rahul Patel',
    age: 30,
    gender: 'Male',
    religion: 'Hindu',
    caste: 'Patel',
    location: 'Ahmedabad',
    bio: 'Business owner with passion for music and sports',
    photo: 'https://randomuser.me/api/portraits/men/1.jpg',
  },
  {
    id: '12',
    name: 'Vikram Singh',
    age: 32,
    gender: 'Male',
    religion: 'Sikh',
    caste: 'Jat',
    location: 'Punjab',
    bio: 'Army officer looking for a life partner',
    photo: 'https://randomuser.me/api/portraits/men/2.jpg',
  },
  {
    id: '13',
    name: 'Arjun Rao',
    age: 28,
    gender: 'Male',
    religion: 'Hindu',
    caste: 'Kshatriya',
    location: 'Hyderabad',
    bio: 'Data scientist who enjoys cricket',
    photo: 'https://randomuser.me/api/portraits/men/3.jpg',
  },
  {
    id: '14',
    name: 'Sameer Khan',
    age: 29,
    gender: 'Male',
    religion: 'Muslim',
    caste: 'Sunni',
    location: 'Mumbai',
    bio: 'Startup founder and fitness enthusiast',
    photo: 'https://randomuser.me/api/portraits/men/4.jpg',
  },
  {
    id: '15',
    name: 'Rohan Sharma',
    age: 26,
    gender: 'Male',
    religion: 'Hindu',
    caste: 'Brahmin',
    location: 'Delhi',
    bio: 'Software developer who loves gaming',
    photo: 'https://randomuser.me/api/portraits/men/5.jpg',
  },
  {
    id: '16',
    name: 'Joseph Mathew',
    age: 31,
    gender: 'Male',
    religion: 'Christian',
    caste: 'Catholic',
    location: 'Chennai',
    bio: 'Chef with a passion for travel',
    photo: 'https://randomuser.me/api/portraits/men/6.jpg',
  },
  {
    id: '17',
    name: 'Amanpreet Singh',
    age: 27,
    gender: 'Male',
    religion: 'Sikh',
    caste: 'Arora',
    location: 'Bangalore',
    bio: 'Product manager and music lover',
    photo: 'https://randomuser.me/api/portraits/men/7.jpg',
  },
  {
    id: '18',
    name: 'Kunal Jain',
    age: 25,
    gender: 'Male',
    religion: 'Jain',
    caste: 'Digambara',
    location: 'Pune',
    bio: 'Financial analyst who enjoys trekking',
    photo: 'https://randomuser.me/api/portraits/men/8.jpg',
  },
  {
    id: '19',
    name: 'Aditya Nair',
    age: 33,
    gender: 'Male',
    religion: 'Hindu',
    caste: 'Nair',
    location: 'Kolkata',
    bio: 'Professor with a love for literature',
    photo: 'https://randomuser.me/api/portraits/men/9.jpg',
  },
  {
    id: '20',
    name: 'Siddharth Bose',
    age: 24,
    gender: 'Male',
    religion: 'Hindu',
    caste: 'Kayastha',
    location: 'Jaipur',
    bio: 'Photographer and adventure enthusiast',
    photo: 'https://randomuser.me/api/portraits/men/10.jpg',
  },
];